sudo: required
dist: trusty
language: python

services:
  - docker

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - ceph-common
      - librados-dev
      - libhdf5-dev
      - libopenmpi-dev
      - openmpi-bin

python:
  - 2.7
  - 3.6

env:
  - ENGINE=cpu BACKEND=ram
  - ENGINE=cpu BACKEND=hdf5
  - ENGINE=cpu BACKEND=ceph
  - ENGINE=mpi BACKEND=ram
  - ENGINE=mpi BACKEND=hdf5
  - ENGINE=mpi BACKEND=ceph

matrix:
  exclude:
    - python: 3.6
      env: ENGINE=cpu BACKEND=ceph
    - python: 3.6
      env: ENGINE=mpi BACKEND=ceph

install:
  - pip install -r requirements.txt
  - pip install -e .

before_script:
  - sudo ./common/start-ceph-in-docker.sh
  - mkdir test-dosna

script:
  - ./run_tests.sh --engine $ENGINE --backend $BACKEND
