language: python

python:
  - 2.7
  - 3.3

addons:
  apt:
    packages:
      - libhdf5-serial-dev

install:
  - pip install -r requirements.txt
  - pip install -e .

env:
  - ENGINE=cpu BACKEND=ram
  - ENGINE=cpu BACKEND=hdf5

script:
  - ./run_tests.sh --engine $ENGINE --backend $BACKEND
